In [ ]:
import numpy as np

docs = ['go india',
        'india india',
        'hip hip hooray',
        'jeetega bhai jeetega india jeetega',
        'bharat mata ki jai',
        'kohli kohli',
        'sachin sachin',
        'dhoni dhoni',
        'modi ji ki jai',
        'inqulab zindabad']

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [ ]:
tokenizer.fit_on_texts(docs)

In [ ]:
len(tokenizer.word_index)

17

In [ ]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [ ]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding
model = Sequential()
model.add(Embedding(17, output_dim=2, input_length=5))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam', 'accuracy')


In [ ]:
import numpy as np
sequences = np.clip(sequences,0, 16)
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step
[[[ 0.01258463  0.00084623]
  [-0.03639206  0.04252057]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]]

 [[-0.03639206  0.04252057]
  [-0.03639206  0.04252057]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]]

 [[ 0.03492327  0.03886416]
  [ 0.03492327  0.03886416]
  [ 0.03534186  0.02873721]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]]

 [[ 0.03338924 -0.03165447]
  [ 0.03335413  0.03613767]
  [ 0.03338924 -0.03165447]
  [-0.03639206  0.04252057]
  [ 0.03338924 -0.03165447]]

 [[ 0.03818697  0.00970377]
  [-0.04240182  0.04724673]
  [ 0.03943298  0.03183446]
  [-0.01077074 -0.04955295]
  [ 0.03179503 -0.00310485]]

 [[ 0.00394535  0.02315129]
  [ 0.00394535  0.02315129]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.00310485]]

 [[-0.0034735   0.0109937 ]
  [-0.0034735   0.0109937 ]
  [ 0.03179503 -0.00310485]
  [ 0.03179503 -0.0031048

In [ ]:
from keras.datasets import imdb
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Embedding, Flatten

In [ ]:
(x_train, y_train), (x_test, y_test) = imdb.load_data(num_words=10000)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
x_train = pad_sequences(x_train, padding='post', maxlen=50)
x_test = pad_sequences(x_test, padding='post', maxlen=50)

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=10000,output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentrop')

In [ ]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=5, validation_data=(x_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 13s 14ms/step - acc: 0.8914 - loss: 0.2770 - val_acc: 0.8035 - val_loss: 0.4431
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 15ms/step - acc: 0.9069 - loss: 0.2461 - val_acc: 0.7937 - val_loss: 0.5207
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 20s 14ms/step - acc: 0.9173 - loss: 0.2296 - val_acc: 0.7958 - val_loss: 0.5103
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 11s 14ms/step - acc: 0.9292 - loss: 0.1981 - val_acc: 0.7902 - val_loss: 0.5095
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 12s 16ms/step - acc: 0.9340 - loss: 0.1874 - val_acc: 0.7840 - val_loss: 0.6266


In [ ]:
# Get the word index used by the IMDB dataset
word_index = imdb.get_word_index()

adjusted_word_index = {word: (index + 3) for word, index in word_index.items()}

# Add special tokens
special_tokens = {
    "<PAD>": 0,
    "<START>": 1,
    "<UNK>": 2,
    "<UNUSED>": 3,
}

word_index = {**special_tokens, **adjusted_word_index}

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
def simple_encode(text):
    words = text.lower().split()
    encoded = [1]  # Start token
    for word in words:
        encoded.append(word_index.get(word, 2))  # Unknown if not found
    return pad_sequences([encoded], maxlen=50, padding='post')

# Your custom sentence
text = "this movie was good and inspiring"

# Encode and predict
encoded = simple_encode(text)
pred = model.predict(encoded)

print("sentiment score:", pred[0][0])
print("prediction:", "Positive 😊" if pred[0][0] >= 0.5 else "Negative 😎")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 249ms/step
sentiment score: 0.9888437
prediction: Positive 😊
